(v1.3.0) jpeg-9f (#4)
* Update libjpeg source to 9f

* Update project version and docs

* Update CI test matrix and add install test

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -3,69 +3,56 @@ name: Build and Test
 on: [push, workflow_dispatch]
 
 env:
-  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
   BUILD_TYPE: Release
 
 jobs:
   build:
-    # The CMake configure and build commands are platform agnostic and should work equally
-    # well on Windows or Mac.  You can convert this to a matrix build if you need
-    # cross-platform coverage.
-    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
-          os: [macos-10.15, macos-11, ubuntu-20.04]
+          os: [macos-11, macos-12, ubuntu-20.04, ubuntu-22.04]
 
     steps:
     - uses: actions/checkout@v2
 
     - name: Setup Ubuntu
-      if: matrix.os == 'ubuntu-20.04'
+      if: startsWith(matrix.os, 'ubuntu')
       run: |
         sudo apt-get update
         sudo apt-get install -y cmake
 
-    - name: Setup macOS 10.15
-      if: matrix.os == 'macos-10.15'
+    - name: Setup macOS
+      if: startsWith(matrix.os, 'macos')
       run: |
         sudo xcode-select -s /Library/Developer/CommandLineTools/
-        sudo rm /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
-        sudo rm -rf /Library/Developer/CommandLineTools/SDKs/MacOSX11*.sdk
-        sudo ln -sf MacOSX10.15.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
+        sudo rm -rf /Library/Frameworks/Mono.framework
         brew install cmake
-
-    - name: Setup macOS 11
-      if: matrix.os == 'macos-11'
-      run: |
-        sudo xcode-select -s /Library/Developer/CommandLineTools/
-        brew install cmake
-
-    - name: Create Build Environment
-      # Some projects don't allow in-source building, so create a separate build directory
-      # We'll use this as our working directory for all subsequent commands
-      run: cmake -E make_directory ${{runner.workspace}}/build
 
     - name: Configure CMake
-      # Use a bash shell so we can use the same syntax for environment variable
-      # access regardless of the host operating system
       shell: bash
-      working-directory: ${{runner.workspace}}/build
-      # Note the current convention is to use the -S and -B options here to specify source
-      # and build directories, but this is only available with CMake 3.13 and higher.
-      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
-      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
+      run: |
+        cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build \
+          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
+          -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install
 
     - name: Build
-      working-directory: ${{runner.workspace}}/build
       shell: bash
       # Execute the build.  You can specify a specific target with "--target <NAME>"
-      run: cmake --build . --config $BUILD_TYPE
+      run: cmake --build ${{runner.workspace}}/build --config $BUILD_TYPE
 
-    - name: Test
+    - name: Test libjpeg
       working-directory: ${{runner.workspace}}/build
       shell: bash
-      # Execute tests defined by the CMake configuration.
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest -V -C $BUILD_TYPE
+
+    - name: Test install
+      shell: bash
+      run: |
+        cmake --install ${{runner.workspace}}/build --config $BUILD_TYPE
+        RESULT=$(cmake --find-package -DNAME=JPEG \
+          -DCOMPILER_ID=GNU -DLANGUAGE=C -DMODE=COMPILE \
+          -DCMAKE_PREFIX_PATH=${{runner.workspace}}/install | awk '{$1=$1};1')
+        [[ "$RESULT" != "-I${{runner.workspace}}/install/include" ]] && { echo "libjpeg not found or found at unexpected location: ${RESULT}" ; exit 1; }
+        exit 0
+        
